security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            stateless: true #no guarda cookies solo devuelve el token
            anonymous: true
            json_login:
                username_path: username
                password_path: password
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            guard:
                authenticators:
                    - App\Security\TokenAuthenticator
            logout:
                path: app_logout

    access_control:
        - { path: ^/admin , roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_GRADUATE:      ROLE_USER
        ROLE_OWNER:         ROLE_USER
        ROLE_ADMIN:         [ ROLE_OWNER, ROLE_GRADUATE]
        ROLE_SUPER_ADMIN:   ROLE_ADMIN
